services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: starter # $7/month
    runtime: docker
    dockerfilePath: Dockerfile.n8n
    healthCheckPath: /
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: N8N_ENCRYPTION_KEY
        sync: false
      - key: N8N_USER_MANAGEMENT_JWT_SECRET
        sync: false
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_PERSONALIZATION_ENABLED
        value: "false"
      - key: N8N_PROTOCOL
        value: "https"
      - key: N8N_HOST
        value: "${RENDER_EXTERNAL_HOSTNAME}"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: EXPRESS_TRUST_PROXY
        value: "true"
      - key: N8N_TRUSTED_PROXIES
        value: "*"
      - key: N8N_METRICS
        value: "false"
      # Default admin user configuration
      - key: N8N_DEFAULT_USER_EMAIL
        sync: false
      - key: N8N_DEFAULT_USER_PASSWORD
        sync: false
      - key: N8N_DEFAULT_USER_FIRSTNAME
        value: "Admin"
      - key: N8N_DEFAULT_USER_LASTNAME
        value: "User"
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10 # $2.50/month

  - type: web
    name: qdrant
    env: docker
    region: oregon
    plan: starter # $7/month
    runtime: docker
    dockerfilePath: Dockerfile.qdrant
    disk:
      name: qdrant-data
      mountPath: /qdrant/storage
      sizeGB: 10 # $2.50/month

databases:
  - name: n8n-db
    databaseName: n8n_production
    user: n8n_user
    ipAllowList: 
      - source: 0.0.0.0/0
        description: everywhere
    region: oregon
    plan: basic-1gb # $23.50/month
    postgresMajorVersion: "16"
    diskSizeGB: 15 # included in plan
